# -*- coding: utf-8 -*-
"""test_handler2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o7vZM8N2mPgcbMifPb3E3u65NITVseEc
"""

import requests
import json
import base64
import time
import os


# List of test cases
samples = [
    {
        "image": "/content/rent.jpg",
        "audio": "/content/rent_women.wav",
        "text": "متاخر عليا ايجار الشقة ومش عارف ادفعه"
    },
    {
        "image": "/content/عقد-ايجار.jpg",
        "audio": "/content/rent_man.wav",
        "text": "محتاجة ادفع الايجار لمكان اعيش فيه انا وولادي"
    },
    {
        "image": "/content/debt_5000.jpg",
        "audio": "/content/debt_for_medicine5000.wav",
        "text":  "مضيت وصل امانة ب 5000 جنية علشان اجيب علاج لوالدتي ومش قادر اسدد "
    },
    {
        "image": "/content/debt_10000.jpg",
        "audio": "/content/debt_for_company_100000.wav",
        "text": "مضيت وصل امانة ب  1000000 علشان اعمل مشروع وفشل ومش عارف اسدد ولا اخرج من الازمة دي "
    },
    {
        "image": "/content/debt_5001.png",
        "audio": "/content/debt_for_family_5000.wav",
        "text": "مضيت وصل امانة ب  5000 لزوم مصاريف المدارس والعيال ومش عارف اسدد وخايف اتسجن "
    }
]

all_results = []


def process_sample(image_path, audio_path, text):

    with open(image_path, "rb") as f:
        image_b64 = base64.b64encode(f.read()).decode("utf-8")

    with open(audio_path, "rb") as f:
        audio_b64 = base64.b64encode(f.read()).decode("utf-8")

    payload = {
        "input": {
            "action": "full_pipeline",
            "user_id": "9876567",
            "text": text,
            "images": [image_b64],
            "audio_base64": audio_b64
        }
    }

    response = requests.post(
        RUN_URL,
        headers=headers,
        json=payload
    )
    response.raise_for_status()

    job_id = response.json()["id"]

    status_url = (
        f"https://api.runpod.ai/v2/"
        f"{ENDPOINT_ID}/status/{job_id}"
    )

    while True:

        r = requests.get(status_url, headers=headers)
        r.raise_for_status()

        data = r.json()
        status = data.get("status")

        print(f"Job {job_id}: {status}")

        if status == "COMPLETED":
            return data.get("output")

        if status in {"FAILED", "CANCELLED", "TIMED_OUT"}:
            return {
                "error": status,
                "details": data
            }

        time.sleep(3)


for idx, sample in enumerate(samples, start=1):

    print(f"\n{'='*50}")
    print(f"Processing sample {idx}/5")
    print(f"{'='*50}")

    output = process_sample(
        sample["image"],
        sample["audio"],
        sample["text"]
    )

    # Save individual JSON
    output_file = f"result_{idx}.json"

    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(
            output,
            f,
            ensure_ascii=False,
            indent=2
        )

    print(f"Saved {output_file}")

    all_results.append({
        "sample_id": idx,
        "image": sample["image"],
        "audio": sample["audio"],
        "output": output
    })


# Save all results together
with open(
    "all_results.json",
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        all_results,
        f,
        ensure_ascii=False,
        indent=2
    )

print("\nFinished all samples.")